(function(){
const KEY='sefaz-adaptive-v1';function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function appState(){try{return JSON.parse(localStorage.getItem('sefaz-al-shorts')||'{}')}catch(e){return{}}}function bank(){return Array.isArray(window.st?.qs)?window.st.qs:(Array.isArray(window.Q)?window.Q:[])}function answers(){return window.st?.ans||appState().ans||{}}
function right(q,a){return String(a||'').toUpperCase()===String(q?.r||'').trim().charAt(0).toUpperCase()}
function record(q,chosen){let s=state(),k=String(q.id),x=s[k]||{attempts:0,correct:0,streak:0,last:0,due:0};x.attempts++;x.last=Date.now();if(right(q,chosen)){x.correct++;x.streak++;let days=[1,3,7,14,30][Math.min(x.streak-1,4)];x.due=Date.now()+days*86400000}else{x.streak=0;x.due=Date.now()+10*60000}s[k]=x;save(s)}
function score(q){let x=state()[String(q.id)],a=answers()[q.id];if(!x)return a?2:4;if(!right(q,a))return 100;if(x.due<=Date.now())return 60-Math.min(x.streak,5)*5;return Math.max(1,20-x.streak*3)}
function smart(n=80){return bank().slice().sort((a,b)=>score(b)-score(a)).slice(0,n)}
function wrong(n=80){return bank().filter(q=>answers()[q.id]&&!right(q,answers()[q.id])).sort((a,b)=>score(b)-score(a)).slice(0,n)}
function topic(q){return String(q.t||q.source_pdf||'').trim()}function diag(){let rows=(window.S||[]).map(s=>{let q=bank().filter(x=>x.s===s),a=q.filter(x=>window.st?.ans?.[x.id]),c=a.filter(x=>right(x,window.st.ans[x.id]));return{s,n:a.length,p:a.length?Math.round(c.length/a.length*100):null}}).filter(x=>x.n).sort((a,b)=>a.p-b.p);return rows}
function topicDiag(subject){let rows={};bank().filter(q=>!subject||q.s===subject).forEach(q=>{let a=window.st?.ans?.[q.id];if(!a)return;let k=topic(q)||'Geral',x=rows[k]||(rows[k]={t:k,n:0,c:0});x.n++;if(right(q,a))x.c++});return Object.values(rows).map(x=>({...x,p:Math.round(x.c/x.n*100)})).sort((a,b)=>a.p-b.p)}
function openReading(q){let p={subject:q.s||'',lesson:window.sefazQuestionLesson?window.sefazQuestionLesson(q):(q.t||'')};localStorage.setItem('sefaz-reading-last-v2',JSON.stringify(p));document.getElementById('nreading')?.click()}
function addQuestionLinks(){document.querySelectorAll('#feed .q[data-id]').forEach(card=>{if(card.querySelector('.adaptiveLinks'))return;let q=bank().find(x=>String(x.id)===String(card.dataset.id));if(!q)return;let d=document.createElement('div');d.className='adaptiveLinks';d.style.cssText='display:flex;gap:7px;margin-top:8px';let b=document.createElement('button');b.textContent='📖 Estudar assunto';b.style.flex='1';b.onclick=()=>openReading(q);d.appendChild(b);card.appendChild(d)})}
function renderDashboard(){let host=document.getElementById('adaptiveCard');if(!host)return;let d=diag(),weak=d[0],due=smart(999).filter(q=>{let x=state()[String(q.id)];return x&&x.due<=Date.now()}).length,wrongN=wrong(999).length;let td=topicDiag(weak?.s).slice(0,5);host.innerHTML='<h3>🧠 Estudo inteligente</h3><p><b>'+due+'</b> revisões programadas • <b>'+wrongN+'</b> questões erradas'+(weak?' • ponto mais fraco: <b>'+weak.s+' ('+weak.p+'%)</b>':'')+'</p>'+(td.length?'<p><small>Assuntos mais frágeis: '+td.map(x=>x.t+' '+x.p+'%').join(' • ')+'</small></p>':'')+'<button class="primary" id="smartReview">Revisão inteligente</button><button class="primary" id="wrongReview" style="margin-top:8px">Estudar meus erros</button>'+(d.length?'<hr><b>Diagnóstico</b>'+d.slice(0,5).map(x=>'<p>'+x.s+': <b>'+x.p+'%</b> • '+x.n+' respondidas</p>').join(''):'');document.getElementById('smartReview').onclick=()=>{window.tab('feed');window.render(smart())};document.getElementById('wrongReview').onclick=()=>{let q=wrong();if(!q.length)return alert('Nenhuma questão errada registrada.');window.tab('feed');window.render(q)}}
function weakSubjects(){return diag().slice(0,3).map(x=>x.s)}
function adaptiveCycle(){let weak=weakSubjects();if(!weak.length)return null;let q=bank().filter(x=>weak.includes(x.s)).sort((a,b)=>score(b)-score(a)).slice(0,80);return q.length?q:null}
window.sefazAdaptive={smart,wrong,diag,weakSubjects,adaptiveCycle,score};
function hook(){if(!window.ans||window.__adaptiveHook)return false;let old=window.ans;window.ans=function(id,l,btn){let q=bank().find(x=>String(x.id)===String(id));let had=q&&answers()[q.id];old(id,l,btn);if(q&&!had)record(q,l);renderDashboard()};window.__adaptiveHook=1;let stats=document.getElementById('stats');if(stats&&!document.getElementById('adaptiveCard')){let d=document.createElement('div');d.id='adaptiveCard';d.className='card';stats.appendChild(d)}let more=document.getElementById('more');if(more&&!document.getElementById('adaptiveMore')){let d=document.createElement('div');d.id='adaptiveMore';d.className='card';d.innerHTML='<h3>🎯 Revisão adaptativa</h3><p>Prioriza erros, revisões vencidas e conteúdos com menor domínio.</p><button class="primary" onclick="tab(\'stats\')">Abrir estudo inteligente</button>';more.insertBefore(d,more.firstChild)}renderDashboard();let feed=document.getElementById('feed');if(feed)new MutationObserver(addQuestionLinks).observe(feed,{childList:true,subtree:true});addQuestionLinks();return true}
let t=setInterval(()=>{if(hook())clearInterval(t)},100);window.addEventListener('storage',renderDashboard);
})();