(function(){
let READING=null;
const STOP=new Set('a o os as de da do das dos e em no na nos nas um uma uns umas para por com sem que se ao aos à às é ser são foi como ou mais menos sobre entre sua seu suas seus este esta isso isto aquele aquela fale falar explique explicar diga dizer quero saber conceito definicao defina'.split(' '));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ç ]/g,' ').replace(/\s+/g,' ').trim();
function terms(q){return [...new Set(norm(q).split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))].slice(0,12)}
function words(text){return norm(text).split(/\s+/).filter(Boolean)}
async function reading(){if(READING)return READING;let r=await fetch('reading-data.json');if(!r.ok)throw Error('material');let j=await r.json();READING=Array.isArray(j)?j:[];return READING}
function questionBank(){for(const x of[window.Q,window.questions,window.__QUESTOES,window.__questions])if(Array.isArray(x)&&x.length)return x;return []}
const DOMAINS=[{name:'Português',subjects:['portugues','língua portuguesa','lingua portuguesa','gramatica'],keys:['verbo','verbos','substantivo','substantivos','adjetivo','adjetivos','adverbio','adverbios','pronome','pronomes','conjuncao','conjuncoes','preposicao','preposicoes','crase','sintaxe','morfologia','concordancia','regencia','pontuacao','ortografia','acentuacao','semantica'],ctx:['gramatical','gramatica','classe de palavras','conjugacao','infinitivo','indicativo','subjuntivo','imperativo','tempo verbal','modo verbal','pessoa verbal','predicado','oracao']},{name:'Direito Tributário',subjects:['direito tributario','reforma'],keys:['tributo','tributos','imposto','impostos','icms','ibs','cbs','credito tributario','lancamento','homologacao'],ctx:['ctn','fato gerador','sujeito passivo','obrigacao tributaria']},{name:'Contabilidade',subjects:['contabilidade geral','contabilidade publica'],keys:['ativo','passivo','patrimonio','balanco','depreciacao','receita','despesa'],ctx:['contabil','debito','credito','demonstracao']}];
function domainFor(q){const qt=terms(q),nq=' '+qt.join(' ')+' ';let best=null,bestScore=0;for(const d of DOMAINS){let s=0;for(const k of d.keys){const nk=norm(k);if(qt.length===1&&qt[0]===nk)s+=40;else if(nq.includes(' '+nk+' '))s+=20}if(s>bestScore){best=d;bestScore=s}}return bestScore?best:null}
function subjectMatches(subject,d){if(!d)return false;const s=norm(subject);return d.subjects.some(x=>s.includes(norm(x)))}
function contextMatches(text,d){if(!d)return 0;const n=' '+norm(text)+' ';let c=0;for(const x of d.ctx)if(n.includes(' '+norm(x)+' '))c++;return c}
function baseScore(text,ts){const ws=words(text),set=new Set(ws);let s=0,matched=0;for(const t of ts){if(set.has(t)){matched++;s+=16;let c=ws.filter(w=>w===t).length;s+=Math.min(c,5)*2}}if(ts.length>1&&matched===ts.length)s+=25;return s}
function score(text,ts,subject,d){let s=baseScore(text,ts);if(!s)return 0;if(d){const sm=subjectMatches(subject,d),cm=contextMatches(text,d);if(sm)s+=220;if(cm)s+=Math.min(cm,5)*12;if(!sm)s-=80}return Math.max(0,s)}
function firstExactIndex(text,ts){const low=String(text||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let best=-1;for(const t of ts){const re=new RegExp('(^|[^a-z0-9ç])'+t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=$|[^a-z0-9ç])','i'),m=re.exec(low);if(m){let p=m.index+(m[1]?m[1].length:0);if(best<0||p<best)best=p}}return best}
function snippet(text,ts){text=String(text||'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();if(!text)return'';let at=firstExactIndex(text,ts);if(at<0)return text.slice(0,760)+(text.length>760?'…':'');let floor=Math.max(0,at-320),start=0;for(let i=at-1;i>=floor;i--){if(/[.!?]/.test(text[i])){start=i+1;break}if(text[i]==='\n'&&i>0&&text[i-1]==='\n'){start=i+1;break}}while(start<text.length&&/[\s,;:.\-–—)\]]/.test(text[start]))start++;let target=Math.min(text.length,start+900),end=target;if(target<text.length){for(let i=target;i<Math.min(text.length,target+180);i++){if(/[.!?]/.test(text[i])){end=i+1;break}}}let s=text.slice(start,end).trim();return s+(end<text.length?'…':'')}
async function search(){let input=document.getElementById('aiQuery'),out=document.getElementById('aiResults'),q=input.value.trim();if(!q){out.innerHTML='<div class="card">Digite um conceito ou dúvida.</div>';return}let ts=terms(q);if(!ts.length){out.innerHTML='<div class="card">Use palavras mais específicas para pesquisar.</div>';return}out.innerHTML='<div class="card">🔎 Pesquisando nos materiais salvos neste aparelho...</div>';try{let rd=await reading(),hits=[],d=domainFor(q);for(const x of rd){let text=[x.subject,x.lesson,x.text].join(' '),s=score(text,ts,x.subject,d);if(s>0)hits.push({s,type:'Leitura',subject:x.subject,lesson:x.lesson,text:x.text,domain:subjectMatches(x.subject,d)})}let qb=questionBank();for(const x of qb){let subject=x.s||x.source_package_canonical||x.source_package||'',text=[subject,x.t,x.q,x.question,x.enunciado,x.c,x.comment,x.comentario,x.explanation].join(' '),s=score(text,ts,subject,d);if(s>0)hits.push({s,type:'Questão',subject,lesson:(window.sefazQuestionLesson&&window.sefazQuestionLesson(x))||x.t||'',text:(x.c||x.comment||x.comentario||x.explanation||x.q||x.question||x.enunciado||''),id:x.id||'',domain:subjectMatches(subject,d)})}hits.sort((a,b)=>b.s-a.s);if(d){let same=hits.filter(h=>h.domain);if(!same.length){out.innerHTML='<div class="card"><b>Não encontrei esse conteúdo em '+esc(d.name)+'.</b><p>Há ocorrências das palavras em outras disciplinas, mas elas foram ignoradas porque não correspondem ao sentido da sua pergunta.</p></div>';return}hits=same}hits=hits.slice(0,8);if(!hits.length){out.innerHTML='<div class="card"><b>Nada encontrado.</b><p>Não encontrei esse conceito nos materiais armazenados.</p></div>';return}let lead=hits[0];out.innerHTML='<div class="card aiAnswer"><b>📌 Trecho mais relevante</b><p>'+esc(snippet(lead.text,ts))+'</p><small>Fonte: '+esc(lead.subject)+(lead.lesson?' • '+esc(lead.lesson):'')+'</small></div>'+(hits.length>1?'<h3>Outras fontes encontradas</h3>'+hits.slice(1).map(h=>'<div class="card"><b>'+esc(h.type)+(h.id?' '+esc(h.id):'')+'</b><p>'+esc(snippet(h.text,ts))+'</p><small>'+esc(h.subject)+(h.lesson?' • '+esc(h.lesson):'')+'</small></div>').join(''):'');}catch(e){out.innerHTML='<div class="card">Não consegui abrir os materiais locais. Se este aparelho ainda não foi preparado para uso offline, conecte-se uma vez e use <b>Mais → Uso offline</b>.</div>'}}
function open(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));document.getElementById('feedFilter')?.classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));let s=document.getElementById('assistant');s.classList.remove('hidden');document.getElementById('nassistant')?.classList.add('on');window.scrollTo(0,0);setTimeout(()=>document.getElementById('aiQuery')?.focus(),80)}
function arrangeNav(nav,b){const reading=document.getElementById('nreading'),more=nav.lastElementChild;if(reading&&reading.nextElementSibling!==b)nav.insertBefore(b,reading.nextSibling);else if(!reading&&b!==more)nav.insertBefore(b,more)}
function init(){let app=document.querySelector('.app'),nav=app&&app.querySelector('nav'),more=document.getElementById('more');if(!app||!nav||!more)return false;if(document.getElementById('assistant')){let b=document.getElementById('nassistant');if(b)arrangeNav(nav,b);return true}let style=document.createElement('style');style.textContent='#assistant{padding-top:125px!important;padding-bottom:95px}.aiSearch{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.aiSearch input{margin:0;min-width:0}.aiSearch button{border:0;border-radius:12px;background:#ffd52e;color:#07182e;font-weight:900;padding:0 16px}.aiAnswer{border-color:#ffd52e}.aiHint{color:#aabbd0;font-size:13px}@media(min-width:700px){#assistant{padding-top:135px!important}}';document.head.appendChild(style);let s=document.createElement('section');s.id='assistant';s.className='panel hidden';s.innerHTML='<h2>🤖 Assistente Offline</h2><p class="aiHint">Pesquisa seus materiais por assunto e disciplina. Expressões como “fale sobre” e “explique” são interpretadas como perguntas, não como palavras de busca.</p><div class="aiSearch"><input id="aiQuery" placeholder="Ex.: fale sobre verbos"><button id="aiGo">Pesquisar</button></div><div id="aiResults"><div class="card">Digite sua dúvida ou um conceito. O assistente localizará os trechos correspondentes nos seus materiais.</div></div>';app.insertBefore(s,nav);document.getElementById('aiGo').onclick=search;document.getElementById('aiQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search()});let notes=document.getElementById('nnotes');let b=document.createElement('button');b.id='nassistant';b.innerHTML='🤖<br>Assistente';b.onclick=open;if(notes)notes.style.display='none';nav.insertBefore(b,nav.lastElementChild);arrangeNav(nav,b);if(!document.getElementById('moreNotesCard')){let d=document.createElement('div');d.id='moreNotesCard';d.className='card';d.innerHTML='<h3>📝 Anotações</h3><p>Consulte, edite, imprima ou faça backup das suas anotações.</p><button class="primary">Abrir Anotações</button>';d.querySelector('button').onclick=()=>window.tabNotes&&window.tabNotes();more.insertBefore(d,more.firstChild)}window.openOfflineAssistant=open;return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>160)clearInterval(t)},50);
})();