(function(){
let READING=null;
const STOP=new Set('a o os as de da do das dos e em no na nos nas um uma uns umas para por com sem que se ao aos à às é ser são foi como ou mais menos sobre entre sua seu suas seus este esta isso isto aquele aquela'.split(' '));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ç ]/g,' ');
function terms(q){return [...new Set(norm(q).split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))].slice(0,12)}
async function reading(){if(READING)return READING;let r=await fetch('reading-data.json');if(!r.ok)throw Error('material');let j=await r.json();READING=Array.isArray(j)?j:[];return READING}
function questionBank(){for(const x of[window.Q,window.questions,window.__QUESTOES,window.__questions])if(Array.isArray(x)&&x.length)return x;return []}
function score(text,ts){let n=norm(text),s=0;for(const t of ts){let p=n.indexOf(t);if(p>=0){s+=3;let c=n.split(t).length-1;s+=Math.min(c,5)}}return s}
function snippet(text,ts){text=String(text||'').replace(/\s+/g,' ').trim();if(!text)return'';let n=norm(text),at=-1;for(const t of ts){let p=n.indexOf(t);if(p>=0&&(at<0||p<at))at=p}if(at<0)return text.slice(0,700);let start=Math.max(0,at-220);if(start>0){let candidates=[];for(let i=start;i<at;i++){let c=text[i];if(c==='.'||c==='!'||c==='?'||c===';'||c===':'||c==='\n')candidates.push(i+1)}if(candidates.length)start=candidates[candidates.length-1];else{let p=text.lastIndexOf(' ',at-120);start=p>0?p+1:0}}let end=Math.min(text.length,start+900);if(end<text.length){let stops=[];for(let i=Math.max(start+350,end-180);i<Math.min(text.length,end+120);i++){let c=text[i];if(c==='.'||c==='!'||c==='?')stops.push(i+1)}if(stops.length)end=stops[0]}let s=text.slice(start,end).trim();s=s.replace(/^[,;:.\-–—)\]]+\s*/,'');if(start>0&&!/^[A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9■●•]/.test(s))s=s.charAt(0).toUpperCase()+s.slice(1);return s+(end<text.length?'…':'')}
async function search(){let input=document.getElementById('aiQuery'),out=document.getElementById('aiResults'),q=input.value.trim();if(!q){out.innerHTML='<div class="card">Digite um conceito ou dúvida.</div>';return}let ts=terms(q);if(!ts.length){out.innerHTML='<div class="card">Use palavras mais específicas para pesquisar.</div>';return}out.innerHTML='<div class="card">🔎 Pesquisando nos materiais salvos neste aparelho...</div>';try{let rd=await reading(),hits=[];for(const x of rd){let text=[x.subject,x.lesson,x.text].join(' '),s=score(text,ts);if(s)hits.push({s,type:'Leitura',subject:x.subject,lesson:x.lesson,text:x.text})}let qb=questionBank();for(const x of qb){let text=[x.s,x.source_package_canonical,x.source_package,x.t,x.q,x.question,x.enunciado,x.c,x.comment,x.comentario,x.explanation].join(' '),s=score(text,ts);if(s)hits.push({s,type:'Questão',subject:x.s||x.source_package_canonical||x.source_package||'',lesson:(window.sefazQuestionLesson&&window.sefazQuestionLesson(x))||x.t||'',text:(x.c||x.comment||x.comentario||x.explanation||x.q||x.question||x.enunciado||''),id:x.id||''})}hits.sort((a,b)=>b.s-a.s);hits=hits.slice(0,8);if(!hits.length){out.innerHTML='<div class="card"><b>Nada encontrado.</b><p>O Assistente Offline responde apenas com o conteúdo existente nos seus materiais. Tente outros termos.</p></div>';return}let lead=hits[0];out.innerHTML='<div class="card aiAnswer"><b>📌 Trecho mais relevante</b><p>'+esc(snippet(lead.text,ts))+'</p><small>Fonte: '+esc(lead.subject)+(lead.lesson?' • '+esc(lead.lesson):'')+'</small></div><h3>Outras fontes encontradas</h3>'+hits.slice(1).map(h=>'<div class="card"><b>'+esc(h.type)+(h.id?' '+esc(h.id):'')+'</b><p>'+esc(snippet(h.text,ts))+'</p><small>'+esc(h.subject)+(h.lesson?' • '+esc(h.lesson):'')+'</small></div>').join('');}catch(e){out.innerHTML='<div class="card">Não consegui abrir os materiais locais. Se este aparelho ainda não foi preparado para uso offline, conecte-se uma vez e use <b>Mais → Uso offline</b>.</div>'}}
function open(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));document.getElementById('feedFilter')?.classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));let s=document.getElementById('assistant');s.classList.remove('hidden');document.getElementById('nassistant')?.classList.add('on');window.scrollTo(0,0);setTimeout(()=>document.getElementById('aiQuery')?.focus(),80)}
function init(){let app=document.querySelector('.app'),nav=app&&app.querySelector('nav'),more=document.getElementById('more');if(!app||!nav||!more)return false;if(document.getElementById('assistant'))return true;let style=document.createElement('style');style.textContent='#assistant{padding-top:80px}.aiSearch{display:grid;grid-template-columns:1fr auto;gap:8px}.aiSearch input{margin:0}.aiSearch button{border:0;border-radius:12px;background:#ffd52e;color:#07182e;font-weight:900;padding:0 16px}.aiAnswer{border-color:#ffd52e}.aiHint{color:#aabbd0;font-size:13px}';document.head.appendChild(style);let s=document.createElement('section');s.id='assistant';s.className='panel hidden';s.innerHTML='<h2>🤖 Assistente Offline</h2><p class="aiHint">Pesquisa somente seus materiais, resumos e questões já carregadas. Não usa internet e não inventa uma resposta fora das fontes.</p><div class="aiSearch"><input id="aiQuery" placeholder="Ex.: lançamento por homologação"><button id="aiGo">Pesquisar</button></div><div id="aiResults"><div class="card">Digite sua dúvida ou um conceito. O assistente localizará os trechos mais relevantes e mostrará a fonte.</div></div>';app.insertBefore(s,nav);document.getElementById('aiGo').onclick=search;document.getElementById('aiQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search()});let notes=document.getElementById('nnotes');let b=document.createElement('button');b.id='nassistant';b.innerHTML='🤖<br>Assistente';b.onclick=open;if(notes){nav.insertBefore(b,notes);notes.style.display='none'}else nav.insertBefore(b,nav.lastElementChild);if(!document.getElementById('moreNotesCard')){let d=document.createElement('div');d.id='moreNotesCard';d.className='card';d.innerHTML='<h3>📝 Anotações</h3><p>Consulte, edite, imprima ou faça backup das suas anotações.</p><button class="primary">Abrir Anotações</button>';d.querySelector('button').onclick=()=>window.tabNotes&&window.tabNotes();more.insertBefore(d,more.firstChild)}window.openOfflineAssistant=open;return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>160)clearInterval(t)},50);
})();