(function(){
const FORMAT='sefaz-al-backup',VERSION=2;
const LEGACY=['answers','favorites','notes','progress'];
function allowed(k){return !!k&&(k.startsWith('sefaz-')||LEGACY.includes(k))}
function collect(){const ls={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(allowed(k))ls[k]=localStorage.getItem(k)}return{format:FORMAT,version:VERSION,createdAt:new Date().toISOString(),origin:location.origin,app:'SEFAZ-AL',localStorage:ls,summary:{keys:Object.keys(ls).length}}}
function exportBackup(){const m=document.getElementById('backupMsg');try{const data=collect(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'),d=new Date().toISOString().slice(0,10);a.href=url;a.download='backup-sefaz-al-v2-'+d+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);if(m)m.textContent='✅ Backup completo exportado: '+data.summary.keys+' conjuntos de dados locais preservados.'}catch(e){if(m)m.textContent='❌ Não foi possível exportar o backup.'}}
function validate(data){if(!data||data.format!==FORMAT||!data.localStorage||typeof data.localStorage!=='object'||Array.isArray(data.localStorage))throw new Error('formato');let entries=Object.entries(data.localStorage).filter(([k])=>allowed(k));if(!entries.length)throw new Error('vazio');return entries}
function importBackup(file){const m=document.getElementById('backupMsg');if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result||'')),entries=validate(data),ver=Number(data.version||1);if(!confirm('Restaurar este backup v'+ver+'? Os dados locais atuais serão substituídos pelos dados presentes no arquivo.')){if(m)m.textContent='Restauração cancelada.';return}const incoming=new Set(entries.map(([k])=>k);for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(allowed(k)&&!incoming.has(k))localStorage.removeItem(k)}for(const [k,v] of entries){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,String(v))}if(m)m.textContent='✅ Backup v'+ver+' restaurado: '+entries.length+' conjuntos de dados. Recarregando...';setTimeout(()=>location.reload(),700)}catch(e){if(m)m.textContent='❌ Arquivo de backup inválido ou incompatível.'}};r.onerror=()=>{if(m)m.textContent='Não foi possível ler o arquivo.'};r.readAsText(file)}
function audit(){let d=collect(),required=['sefaz-al-shorts','sefaz-adaptive-v1','sefaz-al-cycle-p3-v1','sefaz-al-study-v1','sefaz-daily-goals-v1','sefaz-reading-last-v2','sefaz-al-feed-order-v1'],present=required.filter(k=>Object.prototype.hasOwnProperty.call(d.localStorage,k));return{version:d.version,keys:d.summary.keys,recognized:present}}
window.sefazBackup={collect,validate,audit,exportBackup,importBackup};
function inject(){const more=document.getElementById('more');if(!more)return false;if(document.getElementById('backupCard'))return true;const d=document.createElement('div');d.id='backupCard';d.className='card';d.innerHTML='<h3>💾 Backup completo</h3><p>Preserva progresso, respostas, acertos e erros, favoritas, revisão inteligente 1–3–7–14–30, ciclo, aulas concluídas, metas, leitura, anotações e configurações locais.</p><button id="backupExport" class="primary" type="button">⬇️ Exportar backup completo</button><label class="primary" style="display:block;text-align:center;margin-top:10px;cursor:pointer">⬆️ Restaurar backup<input id="backupImport" type="file" accept="application/json,.json" style="display:none"></label><p id="backupMsg"><small>Compatível também com backups antigos do SEFAZ-AL.</small></p>';more.insertBefore(d,more.firstChild);document.getElementById('backupExport').onclick=exportBackup;document.getElementById('backupImport').onchange=e=>{importBackup(e.target.files&&e.target.files[0]);e.target.value=''};return true}
let n=0,t=setInterval(()=>{n++;if(inject()||n>120)clearInterval(t)},50);
})();