(function(){
const KEY='sefaz-al-cycle-timer-v1';let tick=null;
function state(){try{return Object.assign({total:14400,left:14400,running:false,end:0},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return{total:14400,left:14400,running:false,end:0}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function current(s){if(s.running&&s.end)return Math.max(0,Math.ceil((s.end-Date.now())/1000));return Math.max(0,s.left||0)}
function fmt(n){n=Math.max(0,n|0);let h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function draw(){let s=state(),left=current(s);if(s.running&&left<=0){s.running=false;s.left=0;s.end=0;save(s)}let t=document.getElementById('cycleTimerTime'),bar=document.getElementById('cycleTimerBar'),btn=document.getElementById('cycleTimerToggle');if(t)t.textContent=fmt(left)+' restantes';if(bar)bar.style.width=(s.total?Math.min(100,Math.max(0,(s.total-left)/s.total*100)):0)+'%';if(btn)btn.textContent=s.running?'⏸ Pausar':'▶ Iniciar'}
function setMinutes(){let s=state(),v=prompt('Tempo total do ciclo em minutos:',String(Math.round(s.total/60)));if(v===null)return;let min=Number(v);if(!Number.isFinite(min)||min<1||min>1440){alert('Informe um valor entre 1 e 1440 minutos.');return}s.total=Math.round(min*60);s.left=s.total;s.running=false;s.end=0;save(s);draw()}
function toggle(){let s=state(),left=current(s);if(s.running){s.left=left;s.running=false;s.end=0}else{if(left<=0)left=s.total;s.left=left;s.running=true;s.end=Date.now()+left*1000}save(s);draw()}
function reset(){if(!confirm('Reiniciar o marcador do ciclo?'))return;let s=state();s.left=s.total;s.running=false;s.end=0;save(s);draw()}
function init(){if(document.getElementById('cycleTimer'))return true;let app=document.querySelector('.app');if(!app)return false;let style=document.createElement('style');style.textContent='#cycleTimer{position:sticky;top:0;z-index:50;background:#061f39;border-bottom:1px solid #24517c;padding:7px 10px;display:grid;grid-template-columns:1fr auto;gap:5px 8px;align-items:center}#cycleTimerTime{font-weight:700;font-variant-numeric:tabular-nums;font-size:14px}#cycleTimerBtns{display:flex;gap:5px}#cycleTimer button{padding:6px 8px;font-size:12px;border-radius:9px}#cycleTimerTrack{grid-column:1/-1;height:4px;background:#183b5e;border-radius:9px;overflow:hidden}#cycleTimerBar{height:100%;width:0;background:#43e09d;transition:width .3s}@media(min-width:700px){#cycleTimer{padding:8px 18px}#cycleTimerTime{font-size:15px}}';document.head.appendChild(style);let d=document.createElement('div');d.id='cycleTimer';d.innerHTML='<div><small>⏱ Ciclo de estudo</small><div id="cycleTimerTime">04:00:00 restantes</div></div><div id="cycleTimerBtns"><button id="cycleTimerSet" title="Definir tempo">⚙ Tempo</button><button id="cycleTimerToggle">▶ Iniciar</button><button id="cycleTimerReset" title="Reiniciar">↺</button></div><div id="cycleTimerTrack"><div id="cycleTimerBar"></div></div>';app.insertBefore(d,app.firstChild);document.getElementById('cycleTimerSet').onclick=setMinutes;document.getElementById('cycleTimerToggle').onclick=toggle;document.getElementById('cycleTimerReset').onclick=reset;draw();tick=setInterval(draw,1000);return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();