(function(){
let DATA=null,INDEX=null;const VER='dict-v2-275';
const STOP=new Set('a o os as de da do das dos e em no na nos nas um uma uns umas para por com sem que se ao aos à às é ser são foi como ou mais menos sobre entre sua seu suas seus este esta isso isto aquele aquela fale falar explique explicar diga dizer quero saber conceito definicao defina'.split(' '));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ç ]/g,' ').replace(/\s+/g,' ').trim();
function singular(w){w=norm(w);if(w.endsWith('oes')&&w.length>5)return w.slice(0,-3)+'ao';if(w.endsWith('ais')&&w.length>5)return w.slice(0,-3)+'al';if(w.endsWith('res')&&w.length>5)return w.slice(0,-2);if(w.endsWith('s')&&w.length>4)return w.slice(0,-1);return w}
function queryTerms(q){return [...new Set(norm(q).split(/\s+/).filter(w=>w.length>2&&!STOP.has(w)).map(singular))]}
async function data(){if(DATA)return DATA;let r=await fetch('reading-data.json');if(!r.ok)throw Error('material');let j=await r.json();DATA=Array.isArray(j)?j:[];return DATA}
function candidates(text){let out=[],seen=new Set(),lines=String(text||'').split(/\n+/);for(let raw of lines){let line=raw.replace(/^[\s●○■▪•\-–—]+/,'').replace(/^\d+[.)]\s*/,'').trim();if(!line||line.length>190)continue;let m=line.match(/^(.{3,75}?)(?:\s*[:—–]\s+)(.{12,})$/);if(m){let t=m[1].trim(),n=norm(t);if(n.length>=3&&n.length<=75&&!seen.has(n)&&!/^(aula|resumo|item|questao|comentario|resposta|bloco|gabarito)/i.test(n)&&!/[<>{}=\\]/.test(t)){seen.add(n);out.push(t)}}let h=line.match(/^(?:\d+(?:\.\d+)*[.)]?\s*)?([A-ZÁÉÍÓÚÂÊÔÃÕÇ][A-Za-zÀ-ÿ0-9 /()º§.\-]{3,65})$/);if(h){let t=h[1].trim(),n=norm(t);if(n.length>=4&&n.length<=65&&!seen.has(n)&&!/^(aula|resumo|bloco|questao|gabarito|comentario|item)/i.test(n)){seen.add(n);out.push(t)}}}return out}
function sentenceFor(text,title){let nt=norm(title),plain=String(text||'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n');let lines=plain.split(/\n+/),idx=lines.findIndex(x=>norm(x).includes(nt));if(idx>=0){let parts=[];for(let i=idx;i<Math.min(lines.length,idx+5);i++){let x=lines[i].trim();if(!x)break;if(i>idx&&/^(questao|gabarito|comentario|item)\b/i.test(norm(x)))break;parts.push(x);if(parts.join(' ').length>900)break}let s=parts.join(' ').trim();if(s.length>=25)return s.slice(0,900)}let parts=plain.replace(/\s+/g,' ').split(/(?<=[.!?])\s+/),p=parts.find(x=>norm(x).includes(nt));return String(p||'').trim().slice(0,900)}
async function build(){if(INDEX)return INDEX;let rd=await data(),map=new Map();for(const x of rd){let text=String(x.text||''),cs=candidates(text);for(const title of cs){let key=norm(title),def=sentenceFor(text,title);if(def.length<25)continue;if(!map.has(key))map.set(key,{title,sources:[]});let e=map.get(key);if(!e.sources.some(s=>s.subject===x.subject&&s.lesson===x.lesson))e.sources.push({subject:x.subject||'',lesson:x.lesson||'',text:def})}}INDEX=[...map.values()].filter(e=>e.sources.length).sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));try{sessionStorage.setItem(VER,String(INDEX.length))}catch(_){ }paintCount();return INDEX}
function paintCount(){let e=document.getElementById('dictCount');if(e&&INDEX)e.textContent=INDEX.length.toLocaleString('pt-BR')+' conceitos indexados'}
function score(e,ts){let title=singular(e.title),words=new Set(norm(e.title).split(' ').map(singular)),s=0;for(const t of ts){if(title===t)s+=120;if(words.has(t))s+=65;if(title.startsWith(t+' '))s+=35;if(title.includes(t))s+=8}return s}
async function search(){let q=document.getElementById('dictQuery').value.trim(),out=document.getElementById('dictResults');if(!q){out.innerHTML='<div class="card">Digite um termo.</div>';return}let ts=queryTerms(q);if(!ts.length){out.innerHTML='<div class="card">Digite o nome do conceito que deseja consultar.</div>';return}out.innerHTML='<div class="card">📚 Consultando o índice local...</div>';try{let idx=await build(),hits=idx.map(e=>({e,s:score(e,ts)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||a.e.title.localeCompare(b.e.title,'pt-BR')).slice(0,15);if(!hits.length){out.innerHTML='<div class="card"><b>Termo não encontrado.</b><p>Esse conceito não foi identificado nos materiais atualmente carregados.</p></div>';return}let exact=hits[0].s>=65?hits[0].e:null;if(exact){let src=exact.sources[0];out.innerHTML='<div class="card dictEntry"><h2>'+esc(exact.title)+'</h2><p>'+esc(src.text)+'</p><small>📚 '+esc(src.subject)+(src.lesson?' • '+esc(src.lesson):'')+'</small></div>'+(exact.sources.length>1?'<div class="card"><b>Também aparece em</b>'+exact.sources.slice(1,8).map(s=>'<p>'+esc(s.subject)+(s.lesson?' • '+esc(s.lesson):'')+'</p>').join('')+'</div>':'');}else out.innerHTML='<div class="card"><b>Termos próximos</b>'+hits.map(h=>'<button class="dictTerm" data-term="'+esc(h.e.title)+'">'+esc(h.e.title)+'</button>').join('')+'</div>';out.querySelectorAll('.dictTerm').forEach(b=>b.onclick=()=>{document.getElementById('dictQuery').value=b.dataset.term;search()})}catch(e){out.innerHTML='<div class="card">Não consegui abrir o dicionário local.</div>'}}
function open(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));document.getElementById('feedFilter')?.classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));let s=document.getElementById('dictionary');s.classList.remove('hidden');document.getElementById('ndictionary')?.classList.add('on');window.scrollTo(0,0);build();setTimeout(()=>document.getElementById('dictQuery')?.focus(),60)}
function init(){let app=document.querySelector('.app'),nav=app&&app.querySelector('nav');if(!app||!nav)return false;if(document.getElementById('dictionary'))return true;document.getElementById('assistant')?.remove();document.getElementById('nassistant')?.remove();let st=document.createElement('style');st.textContent='#dictionary{padding-top:125px!important;padding-bottom:95px}.dictSearch{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.dictSearch input{margin:0;min-width:0}.dictSearch button{border:0;border-radius:12px;background:#ffd52e;color:#07182e;font-weight:900;padding:0 16px}.dictEntry{border-color:#ffd52e}.dictEntry h2{margin-top:0}.dictTerm{display:block;width:100%;text-align:left;margin:8px 0;padding:12px;border:1px solid #28557a;border-radius:12px;background:#0d3152;color:#fff;font-size:16px}#dictCount{color:#43e09d;font-size:12px;margin-top:4px}@media(min-width:700px){#dictionary{padding-top:135px!important}}';document.head.appendChild(st);let s=document.createElement('section');s.id='dictionary';s.className='panel hidden';s.innerHTML='<h2>📖 Dicionário Offline</h2><p style="color:#aabbd0;font-size:13px">Conceitos extraídos dos materiais de estudo. Funciona sem internet.</p><div id="dictCount">Montando índice de conceitos…</div><div class="dictSearch"><input id="dictQuery" placeholder="Ex.: lançamento por homologação"><button id="dictGo">Pesquisar</button></div><div id="dictResults"><div class="card">Pesquise diretamente pelo nome de um conceito.</div></div>';app.insertBefore(s,nav);document.getElementById('dictGo').onclick=search;document.getElementById('dictQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search()});let b=document.createElement('button');b.id='ndictionary';b.innerHTML='📖<br>Dicionário';b.onclick=open;let reading=document.getElementById('nreading');nav.insertBefore(b,reading?reading.nextSibling:nav.lastElementChild);setTimeout(()=>build(),500);return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>160)clearInterval(t)},50);
})();