(function(){
const KEY='sefaz-al-notes-v1';let editId=null,questionCtx=null;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function all(){try{let a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return []}}
function save(a){localStorage.setItem(KEY,JSON.stringify(a))}
function now(){return new Date().toISOString()}
function catalog(){return window.SEFAZ_STUDY||[]}
function fillSubjects(){let s=document.getElementById('noteSubject');if(!s)return;let cur=s.value;s.innerHTML='<option value="">Sem matéria</option>'+catalog().map(x=>'<option>'+esc(x.subject)+'</option>').join('');s.value=cur;fillLessons()}
function fillLessons(){let su=document.getElementById('noteSubject'),le=document.getElementById('noteLesson');if(!su||!le)return;let cur=le.value,g=catalog().find(x=>x.subject===su.value);le.innerHTML='<option value="">Sem aula</option>'+((g&&g.lessons)||[]).map(x=>'<option>'+esc(x)+'</option>').join('');le.value=cur}
function form(n){n=n||{};editId=n.id||null;document.getElementById('noteTitle').value=n.title||'';document.getElementById('noteText').value=n.text||'';document.getElementById('noteSubject').value=n.subject||'';fillLessons();document.getElementById('noteLesson').value=n.lesson||'';questionCtx=n.question||null;document.getElementById('noteQuestionRef').textContent=questionCtx?('Questão vinculada: '+(questionCtx.id||'')+' • '+(questionCtx.subject||'')):'Sem questão vinculada';document.getElementById('noteCancel').classList.toggle('hidden',!editId)}
window.saveNote=function(){let text=document.getElementById('noteText').value.trim();if(!text){alert('Escreva a anotação.');return}let a=all(),old=editId&&a.find(x=>x.id===editId),n={id:editId||('n'+Date.now()),title:document.getElementById('noteTitle').value.trim(),text,subject:document.getElementById('noteSubject').value,lesson:document.getElementById('noteLesson').value,question:questionCtx,created:old?old.created:now(),updated:now()};if(old)Object.assign(old,n);else a.unshift(n);save(a);form();render()};
window.cancelNote=function(){form()};window.editNote=function(id){let n=all().find(x=>x.id===id);if(n){form(n);document.getElementById('noteText').focus();window.scrollTo(0,0)}};
window.deleteNote=function(id){if(!confirm('Excluir esta anotação?'))return;save(all().filter(x=>x.id!==id));if(editId===id)form();render()};
function render(){let box=document.getElementById('notesList');if(!box)return;let q=(document.getElementById('noteSearch').value||'').toLowerCase(),a=all().filter(n=>[n.title,n.text,n.subject,n.lesson,n.question&&n.question.id].join(' ').toLowerCase().includes(q));document.getElementById('notesCount').textContent=a.length+' anotação(ões)';box.innerHTML=a.length?a.map(n=>'<div class="card"><b>'+esc(n.title||'Anotação')+'</b><div><small>'+esc(n.subject||'Geral')+(n.lesson?' • '+esc(n.lesson):'')+' • '+new Date(n.updated).toLocaleString('pt-BR')+'</small></div><p style="white-space:pre-wrap">'+esc(n.text)+'</p>'+(n.question?'<small>🔗 Questão '+esc(n.question.id||'')+'</small>':'')+'<div class="noteActions"><button onclick="editNote(\''+n.id+'\')">Editar</button><button onclick="deleteNote(\''+n.id+'\')">Excluir</button></div></div>').join(''):'<div class="card">Nenhuma anotação encontrada.</div>'}
window.searchNotes=render;
window.exportNotes=function(){let blob=new Blob([JSON.stringify({version:1,exported_at:now(),notes:all()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='sefaz-al-anotacoes-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
window.importNotes=function(inp){let f=inp.files&&inp.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result),a=Array.isArray(d)?d:d.notes;if(!Array.isArray(a))throw 0;if(confirm('Importar '+a.length+' anotações? As anotações atuais serão mantidas.')){let cur=all(),ids=new Set(cur.map(x=>x.id));a.forEach(n=>{if(n&&n.text){if(ids.has(n.id))n.id='n'+Date.now()+Math.random();cur.push(n)}});save(cur);render()}}catch(e){alert('Arquivo de anotações inválido.')}inp.value=''};r.readAsText(f)};
window.printNotes=function(){let a=all(),q=(document.getElementById('noteSearch').value||'').toLowerCase();a=a.filter(n=>[n.title,n.text,n.subject,n.lesson].join(' ').toLowerCase().includes(q));let w=window.open('','_blank');if(!w){alert('Permita pop-ups para imprimir.');return}w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Anotações SEFAZ-AL</title><style>body{font:14px Arial;max-width:850px;margin:30px auto;color:#111}article{border-bottom:1px solid #bbb;padding:14px 0;break-inside:avoid}h1,h2{margin-bottom:5px}small{color:#555}.txt{white-space:pre-wrap;line-height:1.45}@media print{button{display:none}}</style></head><body><button onclick="print()">Imprimir</button><h1>Anotações de estudo — SEFAZ-AL</h1><p>'+a.length+' anotação(ões) • '+new Date().toLocaleString('pt-BR')+'</p>'+a.map(n=>'<article><h2>'+esc(n.title||'Anotação')+'</h2><small>'+esc(n.subject||'Geral')+(n.lesson?' • '+esc(n.lesson):'')+' • '+new Date(n.updated).toLocaleString('pt-BR')+'</small><div class="txt">'+esc(n.text)+'</div>'+(n.question?'<p><small>Questão vinculada: '+esc(n.question.id||'')+'</small></p>':'')+'</article>').join('')+'</body></html>');w.document.close()};
window.noteCurrentQuestion=function(q){questionCtx={id:q.id||'',subject:q.s||q.source_package_canonical||q.source_package||'',lesson:(window.sefazQuestionLesson&&window.sefazQuestionLesson(q))||q.t||''};tabNotes();fillSubjects();document.getElementById('noteSubject').value=questionCtx.subject;fillLessons();let le=document.getElementById('noteLesson');if([...le.options].some(o=>o.value===questionCtx.lesson))le.value=questionCtx.lesson;document.getElementById('noteQuestionRef').textContent='Questão vinculada: '+questionCtx.id+' • '+questionCtx.subject;document.getElementById('noteText').focus()};
function tabNotes(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));let ff=document.getElementById('feedFilter');if(ff)ff.classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));document.getElementById('notes').classList.remove('hidden');let b=document.getElementById('nnotes');if(b)b.classList.add('on');fillSubjects();render();window.scrollTo(0,0)}window.tabNotes=tabNotes;
function injectQuestionButtons(){document.querySelectorAll('#feed .q').forEach(el=>{if(el.querySelector('.noteQuestion'))return;let id=el.dataset&&el.dataset.id,q=(window.Q||window.questions||[]).find&&((window.Q||window.questions).find(x=>String(x.id)===String(id)));if(!q)return;let b=document.createElement('button');b.className='star noteQuestion';b.textContent='📝 Anotar esta questão';b.onclick=()=>noteCurrentQuestion(q);el.appendChild(b)})}
function init(){let app=document.querySelector('.app'),nav=app&&app.querySelector('nav');if(!app||!nav)return false;if(document.getElementById('notes'))return true;let style=document.createElement('style');style.textContent='.noteActions{display:flex;gap:8px}.noteActions button{padding:8px 12px;border-radius:10px;border:1px solid #24517c;background:#07182e;color:#fff}.noteTools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.noteTools button,.noteTools label{padding:11px;border-radius:12px;border:1px solid #24517c;background:#0b2848;color:#fff;text-align:center}';document.head.appendChild(style);let s=document.createElement('section');s.id='notes';s.className='panel hidden';s.innerHTML='<h2>📝 Anotações</h2><p>Pensamentos e registros livres de estudo. Salvos neste aparelho.</p><input id="noteTitle" placeholder="Título (opcional)"><select id="noteSubject" onchange="fillLessons()"></select><select id="noteLesson"></select><div id="noteQuestionRef" class="card">Sem questão vinculada</div><textarea id="noteText" rows="8" placeholder="Escreva sua anotação..."></textarea><button class="primary" onclick="saveNote()">Salvar anotação</button><button id="noteCancel" class="primary hidden" style="margin-top:8px" onclick="cancelNote()">Cancelar edição</button><hr style="border-color:#24517c;margin:18px 0"><input id="noteSearch" placeholder="Pesquisar anotações" oninput="searchNotes()"><div class="noteTools"><button onclick="printNotes()">🖨️ Imprimir</button><button onclick="exportNotes()">⬇️ Backup</button><label>⬆️ Restaurar<input type="file" accept="application/json" onchange="importNotes(this)" style="display:none"></label></div><p id="notesCount"></p><div id="notesList"></div>';app.insertBefore(s,nav);let b=document.createElement('button');b.id='nnotes';b.innerHTML='📝<br>Anotações';b.onclick=tabNotes;nav.insertBefore(b,nav.lastElementChild);window.fillLessons=fillLessons;fillSubjects();setInterval(injectQuestionButtons,800);return true}let t=setInterval(()=>{if(init())clearInterval(t)},50);
})();