(function(){
function state(){const e=document.getElementById('offlineState');if(!e)return;e.textContent=navigator.onLine?'🟢 Online':'🟠 Offline';e.title=navigator.onLine?'Conectado à internet':'Sem internet — usando conteúdo salvo'}
async function register(){if(!('serviceWorker'in navigator))return null;try{return await navigator.serviceWorker.register('./sw.js?v=58',{scope:'./',updateViaCache:'none'})}catch(e){console.error('SW',e);return null}}
window.prepareOffline=async function(){const b=document.getElementById('offlinePrepare'),msg=document.getElementById('offlineMsg');if(b){b.disabled=true;b.textContent='Preparando...'}if(msg)msg.textContent='Atualizando aplicativo, materiais, dicionário e banco v46 para este aparelho.';try{let reg=await register();await reg.update();await navigator.serviceWorker.ready;let sw=navigator.serviceWorker.controller||(reg&&(reg.active||reg.waiting||reg.installing));if(!sw)throw new Error('Service Worker ainda não está ativo.');sw.postMessage({type:'PREPARE_OFFLINE'});setTimeout(()=>{if(b&&b.disabled){b.disabled=false;b.textContent='📥 Preparar para uso offline'}},60000)}catch(e){if(msg)msg.textContent='Não foi possível preparar agora. Verifique a conexão e tente novamente.';if(b){b.disabled=false;b.textContent='📥 Preparar para uso offline'}}};
navigator.serviceWorker&&navigator.serviceWorker.addEventListener('message',e=>{if(!e.data||e.data.type!=='OFFLINE_READY')return;const b=document.getElementById('offlinePrepare'),msg=document.getElementById('offlineMsg');if(e.data.fail&&e.data.fail.length){if(msg)msg.textContent='Preparação parcial: '+e.data.ok+' de '+e.data.total+' arquivos salvos. Tente novamente com internet.'}else{localStorage.setItem('sefaz-al-offline-ready','1');localStorage.setItem('sefaz-al-offline-date',new Date().toISOString());if(msg)msg.textContent='✅ Pronto para uso offline. Shorts, Ciclo, Leitura, marca-texto, Caneta, Anotações da leitura, Dicionário, Matérias, Desempenho e gravador foram atualizados neste aparelho.'}if(b){b.disabled=false;b.textContent='🔄 Atualizar conteúdo offline'}});
function loadScript(id,src){if(document.getElementById(id))return;let s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.body.appendChild(s)}
function loadExtras(){loadScript('dictionaryScript','./dictionary.js?v=3');loadScript('filterVisibilityScript','./filter-visibility.js?v=2');loadScript('navLayoutScript','./nav-layout.js?v=1');loadScript('readingToolsScript','./reading-tools.js?v=2');loadScript('voiceBridgeScript','./voice-bridge.js?v=1')}
function inject(){let app=document.querySelector('.app');if(!app)return false;if(document.getElementById('offlineState')){loadExtras();return true}let top=document.querySelector('.top');if(top){let s=document.createElement('button');s.id='offlineState';s.style.cssText='border:0;background:none;color:#fff;font-size:11px;padding:0 4px';s.onclick=()=>{let x=document.getElementById('offlineCard');if(x){tab('more');setTimeout(()=>x.scrollIntoView({behavior:"smooth",block:"center"}),100)}};top.appendChild(s)}let more=document.getElementById('more');if(more){let d=document.createElement('div');d.id='offlineCard';d.className='card';let ready=localStorage.getItem('sefaz-al-offline-ready')==='1';d.innerHTML='<h3>📴 Uso offline</h3><p>Baixe o aplicativo e os materiais para estudar sem internet. As áreas de estudo e seus dados locais continuam disponíveis neste aparelho.</p><button id="offlinePrepare" class="primary" onclick="prepareOffline()">'+(ready?'🔄 Atualizar conteúdo offline':'📥 Preparar para uso offline')+'</button><p id="offlineMsg"><small>'+(ready?'Este aparelho já foi preparado. Atualize para receber a versão offline mais recente.':'Faça esta preparação uma vez enquanto estiver conectado.')+'</small></p>';more.insertBefore(d,more.firstChild)}state();loadExtras();return true}
window.addEventListener('online',state);window.addEventListener('offline',state);register();let n=0,t=setInterval(()=>{n++;if(inject()||n>120)clearInterval(t)},50);
})();