(function(){
const KEY='sefaz-reading-highlights-v2';let mode='read',canvas=null,ctx=null,drawing=false,last=null,ro=null,markStart=null,rect=null;
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const loadMarks=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};const saveMarks=o=>localStorage.setItem(KEY,JSON.stringify(o));const lessonKey=()=>{try{let p=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null');return p?(p.subject+'||'+p.lesson):''}catch(e){return''}};
function toolbar(){let r=document.getElementById('reading');if(!r||document.getElementById('readingTools'))return;let t=document.createElement('div');t.id='readingTools';t.innerHTML='<button data-m="read"><span>☝</span><small>Ler</small></button><button data-m="highlight"><span>🖍</span><small>Marcar</small></button><button data-m="pen"><span>✏️</span><small>Caneta</small></button><button data-m="erase"><span>🧽</span><small>Apagar</small></button><button id="readingClear"><span>🗑</span><small>Limpar</small></button>';r.appendChild(t);t.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>setMode(b.dataset.m));t.querySelector('#readingClear').onclick=clearCurrent;setMode('read')}
function setMode(m){mode=m;markStart=null;document.querySelectorAll('#readingTools [data-m]').forEach(b=>b.classList.toggle('on',b.dataset.m===m));if(canvas)canvas.style.pointerEvents=(m==='pen'||m==='erase')?'auto':'none';let txt=document.querySelector('.readingSourceText');if(txt){txt.classList.toggle('markMode',m==='highlight');txt.style.touchAction=m==='highlight'?'pan-y':'auto'}}
function applyMarks(){let txt=document.querySelector('.readingSourceText'),k=lessonKey();if(!txt||!k)return;let raw=txt.dataset.rawText||txt.textContent;txt.dataset.rawText=raw;let arr=loadMarks()[k]||[];if(!arr.length){txt.textContent=raw;return}let spans=arr.filter(p=>p.s>=0&&p.e>p.s&&p.e<=raw.length).sort((a,b)=>a.s-b.s),out='',pos=0;for(const p of spans){if(p.s<pos)continue;out+=esc(raw.slice(pos,p.s))+'<mark class="readingMark">'+esc(raw.slice(p.s,p.e))+'</mark>';pos=p.e}txt.innerHTML=out+esc(raw.slice(pos))}
function offsetAtPoint(txt,x,y){let r=document.caretRangeFromPoint?document.caretRangeFromPoint(x,y):null;if(!r||!txt.contains(r.startContainer))return null;let p=document.createRange();p.selectNodeContents(txt);p.setEnd(r.startContainer,r.startOffset);return p.toString().length}
function saveSpan(a,b){let k=lessonKey(),txt=document.querySelector('.readingSourceText');if(!k||!txt)return;let raw=txt.dataset.rawText||txt.textContent,s=Math.max(0,Math.min(a,b)),e=Math.min(raw.length,Math.max(a,b));if(e<=s)return;let all=loadMarks();all[k]=all[k]||[];all[k].push({s,e});all[k].sort((x,y)=>x.s-y.s);let merged=[];for(const p of all[k]){let q=merged.at(-1);if(q&&p.s<=q.e+1)q.e=Math.max(q.e,p.e);else merged.push({s:p.s,e:p.e})}all[k]=merged;saveMarks(all);applyMarks()}
function bindHighlight(txt){txt.onpointerdown=e=>{if(mode!=='highlight')return;markStart=offsetAtPoint(txt,e.clientX,e.clientY);if(markStart!==null)e.preventDefault()};txt.onpointerup=e=>{if(mode!=='highlight'||markStart===null)return;let o=offsetAtPoint(txt,e.clientX,e.clientY);if(o!==null)saveSpan(markStart,o);markStart=null;e.preventDefault()};txt.onpointercancel=()=>markStart=null}
function wrapCanvas(){let card=document.querySelector('#readingBody .card');if(!card)return;if(canvas&&canvas.parentNode===card)return;if(canvas)canvas.remove();card.style.position='relative';canvas=document.createElement('canvas');canvas.id='readingCanvas';card.appendChild(canvas);fitCanvas();setMode(mode);bindCanvas();if(ro)ro.disconnect();ro=new ResizeObserver(()=>requestAnimationFrame(fitCanvas));ro.observe(card)}
function fitCanvas(){if(!canvas||!canvas.parentElement)return;let card=canvas.parentElement,w=Math.ceil(card.clientWidth),h=Math.ceil(card.scrollHeight);if(canvas.width===w&&canvas.height===h){rect=canvas.getBoundingClientRect();return}canvas.width=w;canvas.height=h;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});ctx.lineCap='round';ctx.lineJoin='round';rect=canvas.getBoundingClientRect()}
function pt(e){return{x:e.clientX-rect.left,y:e.clientY-rect.top}}
function segment(p){if(!last){last=p;return}ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}
function bindCanvas(){const move=e=>{if(!drawing)return;let list=e.getCoalescedEvents?.()||[e];for(let i=0;i<list.length;i++)segment(pt(list[i]));e.preventDefault()};canvas.onpointerdown=e=>{if(mode!=='pen'&&mode!=='erase')return;drawing=true;rect=canvas.getBoundingClientRect();last=pt(e);canvas.setPointerCapture?.(e.pointerId);ctx.globalCompositeOperation=mode==='erase'?'destination-out':'source-over';ctx.strokeStyle='#ffd52e';ctx.lineWidth=mode==='erase'?22:3;ctx.lineCap='round';ctx.lineJoin='round';e.preventDefault()};if('onpointerrawupdate' in canvas)canvas.onpointerrawupdate=move;else canvas.onpointermove=move;canvas.onpointerup=e=>{if(!drawing)return;segment(pt(e));drawing=false;last=null};canvas.onpointercancel=()=>{drawing=false;last=null}}
function clearCurrent(){let k=lessonKey();if(mode==='highlight'&&k){let all=loadMarks();delete all[k];saveMarks(all);let txt=document.querySelector('.readingSourceText');if(txt&&txt.dataset.rawText)txt.textContent=txt.dataset.rawText}else if(canvas&&ctx)ctx.clearRect(0,0,canvas.width,canvas.height)}
function enhance(){toolbar();let txt=document.querySelector('.readingSourceText');if(!txt)return;if(!txt.dataset.rawText)txt.dataset.rawText=txt.textContent;applyMarks();bindHighlight(txt);wrapCanvas()}
const obs=new MutationObserver(()=>setTimeout(enhance,20));function init(){let r=document.getElementById('reading');if(!r)return false;toolbar();let b=document.getElementById('readingBody');if(b)obs.observe(b,{childList:true,subtree:false});setTimeout(enhance,120);return true}
let style=document.createElement('style');style.textContent='#readingTools{position:fixed;z-index:70;right:max(6px,calc((100vw - min(100vw,980px))/2 + 6px));top:50%;transform:translateY(-50%);display:flex;flex-direction:column;gap:5px;padding:6px 5px;background:rgba(6,31,57,.94);border:1px solid #24517c;border-radius:14px;box-shadow:0 6px 20px rgba(0,0,0,.28)}#readingTools button{width:50px;min-height:48px;padding:5px 2px;border-radius:10px;border:1px solid #24517c;background:#07182e;color:#fff;font:600 10px system-ui;display:flex;flex-direction:column;align-items:center;justify-content:center}#readingTools button span{font-size:19px}#readingTools button small{font-size:9px}#readingTools button.on{background:#ffd52e;color:#07182e}.readingMark{background:linear-gradient(transparent 12%,rgba(255,213,46,.78) 12%,rgba(255,213,46,.78) 88%,transparent 88%);color:inherit}.readingSourceText.markMode{user-select:none;-webkit-user-select:none;cursor:crosshair}.readingSourceText{position:relative;z-index:2}#readingCanvas{position:absolute;left:0;top:0;z-index:8;touch-action:none;pointer-events:none;contain:strict;will-change:contents}@media(max-width:699px){#readingTools{right:4px;padding:4px 3px;gap:3px}#readingTools button{width:42px;min-height:42px}#readingTools button small{display:none}body.readingMode #readingBody .card{padding-right:48px}}@media(min-width:700px){body.readingMode #readingBody .card{padding-right:62px}}body:not(.readingMode) #readingTools{display:none!important}';document.head.appendChild(style);let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();