(function(){
const KEY='sefaz-reading-highlights-v1';let mode='read',canvas=null,ctx=null,drawing=false,last=null,ro=null;
const loadMarks=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};
const saveMarks=o=>localStorage.setItem(KEY,JSON.stringify(o));
const lessonKey=()=>{try{let p=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null');return p?(p.subject+'||'+p.lesson):''}catch(e){return''}};
function toolbar(){let r=document.getElementById('reading');if(!r||document.getElementById('readingTools'))return;let t=document.createElement('div');t.id='readingTools';t.innerHTML='<button data-m="read">☝ Ler</button><button data-m="highlight">🖍 Marca-texto</button><button data-m="pen">✏️ Caneta</button><button data-m="erase">🧽 Borracha</button><button id="readingClear">🗑 Limpar</button>';let anchor=document.getElementById('readingStatus');r.insertBefore(t,anchor||r.firstChild);t.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>setMode(b.dataset.m));document.getElementById('readingClear').onclick=clearCurrent;setMode('read')}
function setMode(m){mode=m;document.querySelectorAll('#readingTools [data-m]').forEach(b=>b.classList.toggle('on',b.dataset.m===m));if(canvas)canvas.style.pointerEvents=(m==='pen'||m==='erase')?'auto':'none';let txt=document.querySelector('.readingSourceText');if(txt)txt.classList.toggle('markMode',m==='highlight')}
function applyMarks(){let txt=document.querySelector('.readingSourceText'),k=lessonKey();if(!txt||!k)return;let all=loadMarks(),arr=all[k]||[];if(!arr.length)return;let text=txt.textContent,points=[];arr.forEach(m=>{let i=text.indexOf(m.text,m.near||0);if(i<0)i=text.indexOf(m.text);if(i>=0)points.push({s:i,e:i+m.text.length})});points.sort((a,b)=>b.s-a.s);let html=text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));if(points.length){let chars=[...text];let out='',pos=0;points.sort((a,b)=>a.s-b.s).forEach(p=>{if(p.s<pos)return;out+=esc(text.slice(pos,p.s))+'<mark class="readingMark">'+esc(text.slice(p.s,p.e))+'</mark>';pos=p.e});out+=esc(text.slice(pos));txt.innerHTML=out}}
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function selected(){if(mode!=='highlight')return;let sel=getSelection();if(!sel||sel.isCollapsed)return;let txt=document.querySelector('.readingSourceText');if(!txt||!txt.contains(sel.anchorNode)||!txt.contains(sel.focusNode))return;let value=sel.toString().trim();if(value.length<2)return;let k=lessonKey();if(!k)return;let full=txt.textContent,near=Math.max(0,full.indexOf(value));let all=loadMarks();all[k]=all[k]||[];if(!all[k].some(x=>x.text===value&&Math.abs((x.near||0)-near)<5))all[k].push({text:value,near});saveMarks(all);sel.removeAllRanges();applyMarks()}
function wrapCanvas(){let card=document.querySelector('#readingBody .card');if(!card)return;if(canvas&&canvas.parentNode===card){resize();return}if(canvas)canvas.remove();card.style.position='relative';canvas=document.createElement('canvas');canvas.id='readingCanvas';card.appendChild(canvas);ctx=canvas.getContext('2d');resize();setMode(mode);bindCanvas();if(ro)ro.disconnect();ro=new ResizeObserver(resize);ro.observe(card)}
function resize(){if(!canvas||!canvas.parentElement)return;let r=canvas.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);let old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;old.getContext('2d').drawImage(canvas,0,0);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(canvas.parentElement.scrollHeight*d));canvas.style.width=r.width+'px';canvas.style.height=canvas.parentElement.scrollHeight+'px';ctx=canvas.getContext('2d');ctx.scale(d,d);if(old.width)ctx.drawImage(old,0,0,old.width,old.height,0,0,r.width,canvas.parentElement.scrollHeight)}
function point(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function bindCanvas(){canvas.onpointerdown=e=>{if(mode!=='pen'&&mode!=='erase')return;drawing=true;last=point(e);canvas.setPointerCapture&&canvas.setPointerCapture(e.pointerId);e.preventDefault()};canvas.onpointermove=e=>{if(!drawing)return;let p=point(e);ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(mode==='erase'){ctx.globalCompositeOperation='destination-out';ctx.lineWidth=24}else{ctx.globalCompositeOperation='source-over';ctx.strokeStyle='#ffd52e';ctx.lineWidth=3}ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();last=p;e.preventDefault()};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;last=null}}
function clearCurrent(){let k=lessonKey();if(mode==='highlight'&&k){let all=loadMarks();delete all[k];saveMarks(all);let last=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null');if(last){let evt=new CustomEvent('reading-tools-refresh');document.dispatchEvent(evt)}}else if(canvas&&ctx)ctx.clearRect(0,0,canvas.width,canvas.height)}
function enhance(){toolbar();let txt=document.querySelector('.readingSourceText');if(!txt)return;applyMarks();wrapCanvas();txt.onmouseup=selected;txt.ontouchend=()=>setTimeout(selected,80)}
const obs=new MutationObserver(()=>setTimeout(enhance,0));function init(){let r=document.getElementById('reading');if(!r)return false;toolbar();let body=document.getElementById('readingBody');if(body)obs.observe(body,{childList:true,subtree:false});document.addEventListener('selectionchange',()=>{});document.addEventListener('reading-tools-refresh',()=>{let p=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null');let txt=document.querySelector('.readingSourceText');if(txt&&p)location.reload()});setTimeout(enhance,200);return true}
let style=document.createElement('style');style.textContent='#readingTools{position:sticky;top:0;z-index:45;display:flex;gap:5px;overflow-x:auto;padding:6px 0;background:#061f39}#readingTools button{white-space:nowrap;padding:7px 9px;border-radius:9px;border:1px solid #24517c;background:#07182e;color:#fff;font:600 13px system-ui}#readingTools button.on{background:#ffd52e;color:#07182e;border-color:#ffd52e}.readingMark{background:#ffd52e;color:#07182e;border-radius:2px;padding:0 1px}.readingSourceText.markMode{user-select:text;-webkit-user-select:text;cursor:text}#readingCanvas{position:absolute;left:0;top:0;z-index:8;touch-action:none;pointer-events:none}.readingSourceText{position:relative;z-index:2}@media(min-width:700px){#readingTools button{font-size:14px;padding:8px 11px}}';document.head.appendChild(style);let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();