(function(){
const KEY='sefaz-reading-highlights-v2';let mode='read',canvas=null,ctx=null,drawing=false,last=null,ro=null,markStart=null;
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const loadMarks=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};
const saveMarks=o=>localStorage.setItem(KEY,JSON.stringify(o));
const lessonKey=()=>{try{let p=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null');return p?(p.subject+'||'+p.lesson):''}catch(e){return''}};
function toolbar(){let r=document.getElementById('reading');if(!r||document.getElementById('readingTools'))return;let t=document.createElement('div');t.id='readingTools';t.setAttribute('aria-label','Ferramentas de leitura');t.innerHTML='<button data-m="read" title="Ler"><span>☝</span><small>Ler</small></button><button data-m="highlight" title="Marca-texto"><span>🖍</span><small>Marcar</small></button><button data-m="pen" title="Caneta"><span>✏️</span><small>Caneta</small></button><button data-m="erase" title="Borracha"><span>🧽</span><small>Apagar</small></button><button id="readingClear" title="Limpar"><span>🗑</span><small>Limpar</small></button>';r.appendChild(t);t.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>setMode(b.dataset.m));document.getElementById('readingClear').onclick=clearCurrent;setMode('read')}
function setMode(m){mode=m;markStart=null;document.querySelectorAll('#readingTools [data-m]').forEach(b=>b.classList.toggle('on',b.dataset.m===m));if(canvas)canvas.style.pointerEvents=(m==='pen'||m==='erase')?'auto':'none';let txt=document.querySelector('.readingSourceText');if(txt){txt.classList.toggle('markMode',m==='highlight');txt.style.touchAction=m==='highlight'?'pan-y':'auto'}}
function applyMarks(){let txt=document.querySelector('.readingSourceText'),k=lessonKey();if(!txt||!k)return;let raw=txt.dataset.rawText||txt.textContent;txt.dataset.rawText=raw;let arr=loadMarks()[k]||[];if(!arr.length){txt.textContent=raw;return}let spans=arr.map(m=>({s:m.s,e:m.e})).filter(p=>p.s>=0&&p.e>p.s&&p.e<=raw.length).sort((a,b)=>a.s-b.s);let out='',pos=0;for(const p of spans){if(p.s<pos)continue;out+=esc(raw.slice(pos,p.s))+'<mark class="readingMark">'+esc(raw.slice(p.s,p.e))+'</mark>';pos=p.e}out+=esc(raw.slice(pos));txt.innerHTML=out}
function offsetAtPoint(txt,x,y){let range=null;if(document.caretRangeFromPoint)range=document.caretRangeFromPoint(x,y);else if(document.caretPositionFromPoint){let p=document.caretPositionFromPoint(x,y);if(p){range=document.createRange();range.setStart(p.offsetNode,p.offset);range.collapse(true)}}if(!range||!txt.contains(range.startContainer))return null;let pre=document.createRange();pre.selectNodeContents(txt);pre.setEnd(range.startContainer,range.startOffset);return pre.toString().length}
function saveSpan(a,b){let k=lessonKey(),txt=document.querySelector('.readingSourceText');if(!k||!txt)return;let raw=txt.dataset.rawText||txt.textContent,s=Math.max(0,Math.min(a,b)),e=Math.min(raw.length,Math.max(a,b));if(e-s<1)return;let all=loadMarks();all[k]=all[k]||[];all[k].push({s,e});all[k].sort((x,y)=>x.s-y.s);let merged=[];for(const p of all[k]){let q=merged[merged.length-1];if(q&&p.s<=q.e+1)q.e=Math.max(q.e,p.e);else merged.push({s:p.s,e:p.e})}all[k]=merged;saveMarks(all);applyMarks()}
function bindHighlight(txt){txt.onpointerdown=e=>{if(mode!=='highlight')return;let o=offsetAtPoint(txt,e.clientX,e.clientY);if(o!==null){markStart=o;e.preventDefault()}};txt.onpointerup=e=>{if(mode!=='highlight'||markStart===null)return;let o=offsetAtPoint(txt,e.clientX,e.clientY);if(o!==null)saveSpan(markStart,o);markStart=null;e.preventDefault()};txt.onpointercancel=()=>markStart=null}
function wrapCanvas(){let card=document.querySelector('#readingBody .card');if(!card)return;if(canvas&&canvas.parentNode===card){fitCanvas(false);return}if(canvas)canvas.remove();card.style.position='relative';canvas=document.createElement('canvas');canvas.id='readingCanvas';card.appendChild(canvas);fitCanvas(true);setMode(mode);bindCanvas();if(ro)ro.disconnect();ro=new ResizeObserver(()=>fitCanvas(false));ro.observe(card)}
function fitCanvas(first){if(!canvas||!canvas.parentElement)return;let card=canvas.parentElement,w=Math.max(1,card.clientWidth),h=Math.max(1,card.scrollHeight),d=Math.min(devicePixelRatio||1,2);let targetW=Math.round(w*d),targetH=Math.round(h*d);if(!first&&canvas.width===targetW&&canvas.height===targetH)return;let old=null;if(canvas.width&&canvas.height){old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;old.getContext('2d').drawImage(canvas,0,0)}canvas.width=targetW;canvas.height=targetH;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);if(old)ctx.drawImage(old,0,0,old.width,old.height,0,0,w,h)}
function point(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function strokeSegment(a,b,c){let mx=(b.x+c.x)/2,my=(b.y+c.y)/2;ctx.quadraticCurveTo(b.x,b.y,mx,my);return{x:mx,y:my}}
function bindCanvas(){canvas.onpointerdown=e=>{if(mode!=='pen'&&mode!=='erase')return;drawing=true;let p=point(e);last={prev:p,cur:p};canvas.setPointerCapture&&canvas.setPointerCapture(e.pointerId);ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()};canvas.onpointermove=e=>{if(!drawing)return;let events=e.getCoalescedEvents?e.getCoalescedEvents():[e];for(const ev of events){let p=point(ev);ctx.globalCompositeOperation=mode==='erase'?'destination-out':'source-over';ctx.strokeStyle='#ffd52e';ctx.lineWidth=mode==='erase'?26:3.5;ctx.lineCap='round';ctx.lineJoin='round';let mid=strokeSegment(last.prev,last.cur,p);ctx.lineTo(mid.x,mid.y);last={prev:last.cur,cur:p}}ctx.stroke();e.preventDefault()};canvas.onpointerup=e=>{if(!drawing)return;let p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();drawing=false;last=null};canvas.onpointercancel=()=>{if(drawing){ctx.restore();drawing=false;last=null}}}
function clearCurrent(){let k=lessonKey();if(mode==='highlight'&&k){let all=loadMarks();delete all[k];saveMarks(all);let txt=document.querySelector('.readingSourceText');if(txt&&txt.dataset.rawText)txt.textContent=txt.dataset.rawText}else if(canvas&&ctx){let d=Math.min(devicePixelRatio||1,2);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();ctx.setTransform(d,0,0,d,0,0)}}
function enhance(){toolbar();let txt=document.querySelector('.readingSourceText');if(!txt)return;if(!txt.dataset.rawText)txt.dataset.rawText=txt.textContent;applyMarks();bindHighlight(txt);wrapCanvas()}
const obs=new MutationObserver(()=>setTimeout(enhance,30));function init(){let r=document.getElementById('reading');if(!r)return false;toolbar();let body=document.getElementById('readingBody');if(body)obs.observe(body,{childList:true,subtree:false});setTimeout(enhance,200);return true}
let style=document.createElement('style');style.textContent='#readingTools{position:fixed;z-index:70;right:max(6px,calc((100vw - min(100vw,980px))/2 + 6px));top:50%;transform:translateY(-50%);display:flex;flex-direction:column;gap:5px;padding:6px 5px;background:rgba(6,31,57,.94);border:1px solid #24517c;border-radius:14px;box-shadow:0 6px 20px rgba(0,0,0,.28);backdrop-filter:blur(5px)}#readingTools button{width:50px;min-height:48px;padding:5px 2px;border-radius:10px;border:1px solid #24517c;background:#07182e;color:#fff;font:600 10px system-ui;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px}#readingTools button span{font-size:19px;line-height:1.05}#readingTools button small{font-size:9px;line-height:1.05}#readingTools button.on{background:#ffd52e;color:#07182e;border-color:#ffd52e}.readingMark{background:linear-gradient(transparent 12%,rgba(255,213,46,.78) 12%,rgba(255,213,46,.78) 88%,transparent 88%);color:inherit;border-radius:2px;padding:0 1px}.readingSourceText.markMode{user-select:none;-webkit-user-select:none;cursor:crosshair}.readingSourceText{position:relative;z-index:2}#readingCanvas{position:absolute;left:0;top:0;z-index:8;touch-action:none;pointer-events:none}@media(max-width:699px){#readingTools{right:4px;padding:4px 3px;gap:3px;border-radius:11px}#readingTools button{width:42px;min-height:42px}#readingTools button span{font-size:17px}#readingTools button small{display:none}body.readingMode #readingBody .card{padding-right:48px}}@media(min-width:700px){body.readingMode #readingBody .card{padding-right:62px}}body:not(.readingMode) #readingTools{display:none!important}';document.head.appendChild(style);let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();