(function(){
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function currentQuestion(card){let id=card?.dataset?.id;return (window.st?.qs||[]).find(q=>String(q.id)===String(id))}
function readingTarget(q){if(!q)return null;return{subject:q.s||q.source_package_canonical||q.source_package||'',lesson:(window.sefazQuestionLesson&&window.sefazQuestionLesson(q))||q.t||''}}
function openReading(q){let p=readingTarget(q);if(!p)return;localStorage.setItem('sefaz-reading-last-v2',JSON.stringify(p));let b=document.getElementById('nreading');if(b)b.click();else alert('A área Leitura ainda está carregando.')}
function trainReading(){let p;try{p=JSON.parse(localStorage.getItem('sefaz-reading-last-v2')||'null')}catch(e){}if(!p)return;let qs=(window.st?.qs||[]).filter(q=>norm(q.s)===norm(p.subject)&&(norm((window.sefazQuestionLesson&&window.sefazQuestionLesson(q))||q.t).includes(norm(p.lesson))||norm(p.lesson).includes(norm((window.sefazQuestionLesson&&window.sefazQuestionLesson(q))||q.t))));if(!qs.length)qs=(window.st?.qs||[]).filter(q=>norm(q.s)===norm(p.subject));if(!qs.length)return alert('Não encontrei questões vinculadas a esta leitura.');window.tab('feed');window.render(qs.slice(0,80))}
function wireCards(){document.querySelectorAll('#feed .q[data-id]').forEach(card=>{if(card.dataset.studyLink)return;card.dataset.studyLink='1';let q=currentQuestion(card),slot=card.querySelector('.feedback-slot');if(!slot)return;let b=document.createElement('button');b.className='studyLinkBtn';b.textContent='📖 Estudar este assunto';b.onclick=()=>openReading(q);slot.insertAdjacentElement('afterend',b)})}
function readingButton(){let body=document.getElementById('readingBody');if(!body||document.getElementById('trainReading'))return;let b=document.createElement('button');b.id='trainReading';b.className='primary';b.textContent='🎯 Treinar este conteúdo';b.onclick=trainReading;body.insertAdjacentElement('beforebegin',b)}
function weakSubjects(){let S=window.S||[],qs=window.st?.qs||[],ans=window.st?.ans||{};return S.map(s=>{let a=qs.filter(q=>q.s===s&&ans[q.id]),c=a.filter(q=>String(ans[q.id]).toUpperCase()===String(q.r||'').trim().charAt(0).toUpperCase());return{s,n:a.length,p:a.length?c.length/a.length:1}}).filter(x=>x.n).sort((a,b)=>a.p-b.p)}
function adaptCycle(){let box=document.getElementById('studyCyclePlan');if(!box)return;let weak=weakSubjects().slice(0,3);let old=document.getElementById('cycleAdaptiveTip');if(old)old.remove();if(!weak.length)return;let d=document.createElement('div');d.id='cycleAdaptiveTip';d.className='card';d.innerHTML='<b>🧠 Prioridade adaptativa</b><p>Seu desempenho indica reforço em: '+weak.map(x=>x.s+' ('+Math.round(x.p*100)+'%)').join(' • ')+'</p><button class="primary">Treinar matérias prioritárias</button>';d.querySelector('button').onclick=()=>{let names=new Set(weak.map(x=>x.s)),q=(window.st?.qs||[]).filter(x=>names.has(x.s));window.tab('feed');window.render(q.slice(0,80))};box.prepend(d)}
function tick(){wireCards();readingButton();adaptCycle()}
new MutationObserver(()=>setTimeout(tick,20)).observe(document.documentElement,{childList:true,subtree:true});setInterval(tick,1500);tick();
})();