const CACHE='sefaz-al-offline-v81';
const QUESTION_PARTS=['./questoes-originais-shorts-v46-parte-1.json','./questoes-originais-shorts-v46-parte-2.json','./questoes-originais-shorts-v46-parte-3.json'];
const SHELL=['./','./index.html','./manifest.webmanifest','./icon-192.svg','./icon-512.svg','./study.js','./study-open-fix.js','./study-cycle-plan.js','./reading.js','./reading-tools.js','./notes.js','./dictionary.js','./filter-visibility.js','./nav-layout.js','./offline.js','./adaptive-study.js','./study-links.js','./study-integration.js','./voice-bridge.js','./pwa.js','./backup.js','./cycle-timer.js','./cycle-navigator.js','./tablet.css'];
const LARGE=new Set([...QUESTION_PARTS,'./reading-data.json']);
const CORE=[...SHELL,...LARGE];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(async c=>{for(const url of SHELL){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await c.put(url,r.clone())}catch(_){}}}))});
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data&&e.data.type==='PREPARE_OFFLINE'){e.waitUntil(caches.open(CACHE).then(async c=>{let ok=0,fail=[];for(const url of CORE){try{let r;if(LARGE.has(url)){const hit=await c.match(url);r=hit||await fetch(url,{cache:'reload'})}else r=await fetch(url,{cache:'reload'});if(!r||!r.ok)throw new Error(String(r&&r.status));if(!LARGE.has(url)||!(await c.match(url)))await c.put(url,r.clone());ok++}catch(err){fail.push(url)}}try{await buildAndCacheCombinedBank(c)}catch(err){fail.push('./questoes.json')}if(e.source)e.source.postMessage({type:'OFFLINE_READY',ok,fail,total:CORE.length})}))}});
async function loadQuestionPart(url){const cache=await caches.open(CACHE);const cached=await cache.match(url);if(cached){try{return await cached.json()}catch(_){}}const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const clone=r.clone();await cache.put(url,clone);return r.json()}
async function buildAndCacheCombinedBank(cache){const ready=await cache.match('./questoes.json');if(ready)return ready;let questions=[],base={};for(const url of QUESTION_PARTS){const d=await loadQuestionPart(url);if(!Object.keys(base).length&&d&&typeof d==='object'&&!Array.isArray(d))base=d;const arr=Array.isArray(d)?d:(Array.isArray(d.questions)?d.questions:(Array.isArray(d.questoes)?d.questoes:[]));questions.push(...arr)}if(!questions.length)throw new Error('Banco v46 sem questões');const body=JSON.stringify({bank_version:46,updated_at:base.updated_at||'2026-10-03',total_questions:questions.length,questions});const response=new Response(body,{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});await cache.put('./questoes.json',response.clone());return response}
async function combinedQuestionBank(){const cache=await caches.open(CACHE);const ready=await cache.match('./questoes.json');if(ready)return ready;return buildAndCacheCombinedBank(cache)}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;const rel='./'+u.pathname.replace(/^\/app-sefaz-al\//,'');const asksLegacyBank=/\/questoes\.json$/i.test(u.pathname);if(asksLegacyBank){e.respondWith(combinedQuestionBank());return}if(e.request.mode==='navigate'){e.respondWith(caches.match('./index.html').then(hit=>hit||fetch(e.request).then(r=>{if(r&&r.ok)caches.open(CACHE).then(c=>c.put('./index.html',r.clone()));return r})));return}if(LARGE.has(rel)){e.respondWith(caches.match(rel).then(hit=>hit||fetch(e.request).then(r=>{if(r&&r.ok)caches.open(CACHE).then(c=>c.put(rel,r.clone()));return r})));return}const dynamic=/\.(?:js|css|json)$/i.test(u.pathname);if(dynamic){e.respondWith(caches.match(e.request).then(hit=>hit||caches.match(rel)).then(hit=>hit||fetch(e.request).then(r=>{if(r&&r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone()));return r})));return}e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{if(r&&r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone()));return r})))});